# -*- coding: utf-8 -*-
"""social-media-analysis .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CWWdkpgv-er412VuMHE9MtvyrUNGvPIS

### IMPORT LIBRARY
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

"""### LOAD DATA"""

df=pd.read_csv("/kaggle/input/social-media-sentiments-analysis-dataset/sentimentdataset.csv")

"""### DATA EXPLORATION"""

df.shape

df.describe().loc[['min', '50%', 'mean', 'max', 'std']].T.style.background_gradient(axis=1)

df.info()

df.isna().sum()

df_columns=df.columns
for col in df.columns:
    print(col)

df.head()

df.duplicated().any()

"""### VISUALIZATION ON DATA"""

sns.pairplot(df, hue = 'Platform',corner=True )

sns.displot(df.Likes)

sns.displot(df.Platform ,fill=True)

sns.countplot(x = 'Platform' , data = df)
plt.show()

sns.histplot(df['Likes'],bins=20,color='Blue',edgecolor='Red',kde=True)
plt.xlabel("likes")
plt.ylabel("platform")
plt.title("likes_of_platform")

sns.regplot(data = df , x ='Hour' , y ='Likes')

sns.scatterplot(data = df , x ='Hour' , y ='Likes')

plot = sns.PairGrid(df)
plot.map(plt.plot)
plt.show()

df['Sentiment'].value_counts().nlargest(10).plot(kind='bar')
plt.title('Top 10 Sentiments based on Text')
plt.xlabel('Sentiment')
plt.ylabel('text')
plt.show()

df['Platform'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title('Percentages of Platforms')
plt.legend()
plt.show()

df['Country'].value_counts().nlargest(10).plot(kind='bar')
plt.title('Based on Country')
plt.xlabel('Country')
plt.ylabel('Count')
plt.show()

H_retweet= df.groupby('Hashtags')['Retweets'].max().value_counts().nlargest(10).sort_values(ascending=True).plot(kind='bar')